import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://xealkhalej-backend.alwajez.com/api"; // Replace with your actual base URL

// Function to create request
const createRequest = (url) => ({ url });

// Create the API slice using RTK Query
export const apiService = createApi({
  reducerPath: "apiService",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({
    // Example login request (modify this as per your API endpoint)
    loginUser: builder.mutation({
      query: (userCredentials) => ({
        url: "/user/login",
        method: "POST",
        body: userCredentials, // Sending user credentials (email and password)
      }),
    }),

    // You can add more endpoints here as needed
    getUserProfile: builder.query({
      query: (userId) => createRequest(`/users/${userId}`),
    }),
  }),
});

// Export hooks generated by the API service
export const { useLoginUserMutation, useGetUserProfileQuery } = apiService;
